# Generated by Django 2.1 on 2018-08-21 15:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.TextField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.TextField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.FloatField()),
                ('exptime', models.DateField()),
                ('logtime', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('is_approx', models.BooleanField(default=False)),
                ('is_expence', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expences.Category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expences.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Expuser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expences.Category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expences.Currency')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.TextField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='expuser',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expences.Location'),
        ),
        migrations.AddField(
            model_name='expence',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expences.Location'),
        ),
        migrations.AddField(
            model_name='expence',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expences.Expuser'),
        ),
    ]
